"""
tests/test_multi_pole.py — Parametric multi-pole geometry and mesh tests.

Tests that the toolchain works correctly for Qp = 2, 4, 6, 8, 10, 12, 14, 16, 18, 20.

Fast tests (check_only=True, no mesh):  run always.
Slow tests (full mesh):                 run with  pytest -m slow
SIF tests:                              check gen_sif() produces valid output.
"""
from __future__ import annotations

import sys
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).parent.parent))

from motor_params import motor_params_for_poles
from gen_rotor import build_rotor
from gen_stator import build_stator
from gen_sif import gen_sif
from winding_config import winding_phase_map

# Pole counts to test
ALL_QP = [2, 4, 6, 8, 10, 12, 14, 16, 18, 20]

# Subset for slow mesh tests (representative spread)
MESH_QP = [2, 4, 8, 12, 20]


# ─────────────────────────────────────────────────────────────────────────────
#  motor_params_for_poles() — analytical checks (no gmsh)
# ─────────────────────────────────────────────────────────────────────────────
class TestMotorParamsForPoles:
    @pytest.mark.parametrize("Qp", ALL_QP)
    def test_validates(self, Qp):
        """Params generated by factory must pass full validation."""
        p = motor_params_for_poles(Qp)
        p.validate()  # raises if invalid

    @pytest.mark.parametrize("Qp", ALL_QP)
    def test_slot_count(self, Qp):
        p = motor_params_for_poles(Qp)
        assert p.Qs == 6 * Qp
        assert p.ns == 6

    @pytest.mark.parametrize("Qp", ALL_QP)
    def test_magnet_corners_inside_rotor(self, Qp):
        """Inner magnet corners must lie within R_ro."""
        import math
        p = motor_params_for_poles(Qp)
        # inner corner radius = sqrt(R_mi² + (w_mag/2)²)
        r_corner = math.sqrt(p.R_mi**2 + (p.w_mag / 2)**2)
        assert r_corner <= p.R_ro + 1e-6, (
            f"Qp={Qp}: inner corner r={r_corner:.3f} > R_ro={p.R_ro:.3f}"
        )

    @pytest.mark.parametrize("Qp", ALL_QP)
    def test_tooth_widths_positive(self, Qp):
        p = motor_params_for_poles(Qp)
        assert p.tooth_tip_width  > 0, f"Qp={Qp}: tooth_tip_width={p.tooth_tip_width:.3f}"
        assert p.tooth_body_width > 0, f"Qp={Qp}: tooth_body_width={p.tooth_body_width:.3f}"

    @pytest.mark.parametrize("Qp", ALL_QP)
    def test_fill_factor_in_range(self, Qp):
        p = motor_params_for_poles(Qp)
        assert 0.25 <= p.fill_factor <= 0.85, (
            f"Qp={Qp}: fill_factor={p.fill_factor*100:.1f}%"
        )

    @pytest.mark.parametrize("Qp", ALL_QP)
    def test_b_slot_wider_than_b1(self, Qp):
        p = motor_params_for_poles(Qp)
        assert p.b_slot >= p.b1, (
            f"Qp={Qp}: b_slot={p.b_slot} < b1={p.b1}"
        )


# ─────────────────────────────────────────────────────────────────────────────
#  winding_phase_map()
# ─────────────────────────────────────────────────────────────────────────────
class TestWindingPhaseMap:
    def test_ns6(self):
        assert winding_phase_map(6) == ["A+", "A+", "C-", "C-", "B+", "B+"]

    def test_ns3(self):
        assert winding_phase_map(3) == ["A+", "C-", "B+"]

    def test_ns12(self):
        pm = winding_phase_map(12)
        assert len(pm) == 12
        # Each phase occupies 4 consecutive slots
        assert pm[:4]  == ["A+"] * 4
        assert pm[4:8] == ["C-"] * 4
        assert pm[8:]  == ["B+"] * 4

    def test_not_divisible_by_3_raises(self):
        with pytest.raises(ValueError):
            winding_phase_map(5)


# ─────────────────────────────────────────────────────────────────────────────
#  Geometry classification (check_only=True — no mesh, fast)
# ─────────────────────────────────────────────────────────────────────────────
class TestRotorGeometry:
    @pytest.mark.parametrize("Qp", ALL_QP)
    def test_rotor_classification(self, Qp):
        p = motor_params_for_poles(Qp)
        r = build_rotor(p, check_only=True)
        assert len(r["rotor_iron"]) >= 1, f"Qp={Qp}: no rotor iron"
        assert len(r["magnet"])     == 1, f"Qp={Qp}: expected 1 magnet, got {len(r['magnet'])}"
        assert len(r["shaft"])      == 1, f"Qp={Qp}: expected 1 shaft, got {len(r['shaft'])}"
        assert len(r["gap_rotor"])  == 1, f"Qp={Qp}: expected 1 gap_rotor, got {len(r['gap_rotor'])}"

    @pytest.mark.parametrize("Qp", ALL_QP)
    def test_rotor_air_pockets(self, Qp):
        p = motor_params_for_poles(Qp)
        r = build_rotor(p, check_only=True)
        # 2 air pockets (one on each side of the magnet)
        assert len(r["air_pocket"]) == 2, (
            f"Qp={Qp}: expected 2 air pockets, got {len(r['air_pocket'])}"
        )


class TestStatorGeometry:
    @pytest.mark.parametrize("Qp", ALL_QP)
    def test_stator_classification(self, Qp):
        p = motor_params_for_poles(Qp)
        r = build_stator(p, check_only=True)
        assert len(r["stator_iron"]) >= 1, f"Qp={Qp}: no stator iron"
        assert len(r["gap_stator"])  == 1, f"Qp={Qp}: expected 1 gap_stator"

    @pytest.mark.parametrize("Qp", ALL_QP)
    def test_all_slots_classified(self, Qp):
        p = motor_params_for_poles(Qp)
        r = build_stator(p, check_only=True)
        for i in range(p.ns):
            assert len(r["slot_opening"][i]) == 1, (
                f"Qp={Qp} slot {i}: expected 1 opening, got {len(r['slot_opening'][i])}"
            )
            n_hp = sum(len(r["slot_hp"][i][k]) for k in range(p.n_hp))
            assert n_hp == p.n_hp, (
                f"Qp={Qp} slot {i}: expected {p.n_hp} HP layers, got {n_hp}"
            )


# ─────────────────────────────────────────────────────────────────────────────
#  SIF generation — check output is syntactically complete
# ─────────────────────────────────────────────────────────────────────────────
class TestSIF:
    @pytest.mark.parametrize("Qp", ALL_QP)
    def test_sif_generates(self, tmp_path, Qp):
        p = motor_params_for_poles(Qp)
        sif_path = tmp_path / f"case_qp{Qp}.sif"
        gen_sif(p, out_path=sif_path)
        text = sif_path.read_text()
        # Basic structural checks
        assert "Simulation" in text
        assert "Body Force" in text
        assert f"ns={p.ns}" not in text   # should expand slot info, not leave placeholder
        # Phase names appear in body force sections
        assert "A+" in text or "a+" in text.lower()

    @pytest.mark.parametrize("Qp", ALL_QP)
    def test_sif_slot_count_matches(self, tmp_path, Qp):
        """SIF must have exactly ns × n_hp HP body sections."""
        import re
        p = motor_params_for_poles(Qp)
        sif_path = tmp_path / f"case_qp{Qp}.sif"
        gen_sif(p, out_path=sif_path)
        text = sif_path.read_text()
        # Each HP body has exactly one "Name = S{i}_HP{k}_..." line
        n_hp_bodies = len(re.findall(r"Name = S\d+_HP\d+_", text))
        expected = p.ns * p.n_hp
        assert n_hp_bodies == expected, (
            f"Qp={Qp}: expected {expected} HP body Name lines, found {n_hp_bodies}"
        )


# ─────────────────────────────────────────────────────────────────────────────
#  Full mesh tests — marked slow, skipped by default
# ─────────────────────────────────────────────────────────────────────────────
@pytest.mark.slow
class TestMesh:
    @pytest.mark.parametrize("Qp", MESH_QP)
    def test_rotor_meshes(self, tmp_path, Qp):
        p = motor_params_for_poles(Qp)
        out = tmp_path / f"rotor_qp{Qp}.msh"
        r = build_rotor(p, mesh_out=out)
        assert r["n_nodes"]  > 100, f"Qp={Qp}: too few nodes ({r['n_nodes']})"
        assert r["n_elems"]  > 100, f"Qp={Qp}: too few elements ({r['n_elems']})"
        assert out.exists(), f"Qp={Qp}: mesh file not written"
        # Boundary groups must be populated
        assert len(r["sb_rotor"])    >= 1, f"Qp={Qp}: missing SB_Rotor"
        assert len(r["rotor_right"]) >= 1, f"Qp={Qp}: missing Rotor_Right"
        assert len(r["rotor_left"])  >= 1, f"Qp={Qp}: missing Rotor_Left"

    @pytest.mark.parametrize("Qp", MESH_QP)
    def test_stator_meshes(self, tmp_path, Qp):
        p = motor_params_for_poles(Qp)
        out = tmp_path / f"stator_qp{Qp}.msh"
        r = build_stator(p, mesh_out=out)
        assert r["n_nodes"] > 100, f"Qp={Qp}: too few nodes ({r['n_nodes']})"
        assert r["n_elems"] > 100, f"Qp={Qp}: too few elements ({r['n_elems']})"
        assert out.exists(), f"Qp={Qp}: mesh file not written"
        assert len(r["sb_stator"])    >= 1, f"Qp={Qp}: missing SB_Stator"
        assert len(r["domain"])       >= 1, f"Qp={Qp}: missing Domain"
        assert len(r["stator_right"]) >= 1, f"Qp={Qp}: missing Stator_Right"
        assert len(r["stator_left"])  >= 1, f"Qp={Qp}: missing Stator_Left"
